blank_issues_enabled: true
contact_links:
  - name: Issue with ABP Commercial
    url:  https://abp.io/support/questions
    about: Please open ABP Commercial related issues at https://abp.io/support/questions.
  - name: Ask a question (community support)
    url:  https://stackoverflow.com/questions/tagged/abp
    about: Ask a question that will be answered by the ABP community
