version: '3.4'

services:
  sqlserver:
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  volo-docs:
    environment:
      - ConnectionString=Server=sqlserver;Database=VoloDocs;Trusted_Connection=True;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - Title=VoloDocs
      - LogoUrl=/assets/images/Logo.png
    ports:
      - "80:80"
