apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend-admin-app-gateway
  name: backend-admin-app-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: backend-admin-app-gateway
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: AuthServer__Authority
          value: http://auth-server:51511
        - name: ConnectionStrings__Default
          value: Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
        - name: GlobalConfiguration__BaseUrl
          value: http://backend-admin-app-gateway
        - name: ReRoutes__0__DownstreamHostAndPorts__0__Host
          value: identity-service
        - name: ReRoutes__0__DownstreamHostAndPorts__0__Port
          value: "80"
        - name: ReRoutes__1__DownstreamHostAndPorts__0__Host
          value: product-service
        - name: ReRoutes__1__DownstreamHostAndPorts__0__Port
          value: "80"
        - name: Redis__Configuration
          value: redis
        - name: RemoteServices__Default__BaseUrl
          value: http://backend-admin-app-gateway/
        image: volosoft/microservice-demo-backend-admin-app-gateway
        name: backend-admin-app-gateway
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
