apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: blogging-service
  name: blogging-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: blogging-service
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: AuthServer__Authority
          value: http://auth-server:51511
        - name: ConnectionStrings__Blogging
          value: mongodb://mongodb|MsDemo_Blogging
        - name: ConnectionStrings__Default
          value: Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
        - name: RabbitMQ__Connections__Default__HostName
          value: rabbitmq
        - name: Redis__Configuration
          value: redis
        - name: RemoteServices__Default__BaseUrl
          value: http://internal-gateway/
        image: volosoft/microservice-demo-blogging-service
        name: blogging-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
