apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: internal-gateway
  name: internal-gateway
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    io.kompose.service: internal-gateway
status:
  loadBalancer: {}
