apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: public-website
  name: public-website
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: public-website
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: AuthServer__Authority
          value: http://auth-server:51511
        - name: Redis__Configuration
          value: redis
        - name: RemoteServices__Default__BaseUrl
          value: http://public-website-gateway/
        image: volosoft/microservice-demo-public-website
        name: public-website
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
