name: 'Angular'
on:
  pull_request:
    paths:
      - 'npm/ng-packs/**/*.ts'
      - 'npm/ng-packs/**/*.html'
      - 'npm/ng-packs/*.json'
      - '!npm/ng-packs/scripts/**'
      - '!npm/ng-packs/packages/schematics/**'
    branches:
      - 'rel-*'
      - 'dev'
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: 'npm/ng-packs/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('npm/ng-packs/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: 'templates/app/angular/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('templates/app/angular/yarn.lock') }}

      - name: Install packages
        run: yarn install
        working-directory: npm/ng-packs

      - name: Run lint
        run: yarn affected:lint --base=remotes/origin/${{ github.base_ref }}
        working-directory: npm/ng-packs

      - name: Run build
        run: yarn affected:build --base=remotes/origin/${{ github.base_ref }}
        working-directory: npm/ng-packs

      - name: Run test
        run: yarn affected:test --base=remotes/origin/${{ github.base_ref }}
        working-directory: npm/ng-packs
