name: "build and test"
on:
  push:
    branches:
      - dev
    paths:
      - 'framework/**/*.cs'
      - 'framework/**/*.cshtml'
      - 'framework/**/*.csproj'
      - 'framework/**/*.razor'
      - 'modules/**/*.cs'
      - 'modules/**/*.cshtml'
      - 'modules/**/*.csproj'
      - 'modules/**/*.razor'
      - 'templates/**/*.cs'
      - 'templates/**/*.cshtml'
      - 'templates/**/*.csproj'
      - 'templates/**/*.razor'

  pull_request:
    paths:
      - 'framework/**/*.cs'
      - 'framework/**/*.cshtml'
      - 'framework/**/*.csproj'
      - 'framework/**/*.razor'
      - 'modules/**/*.cs'
      - 'modules/**/*.cshtml'
      - 'modules/**/*.csproj'
      - 'modules/**/*.razor'
      - 'templates/**/*.cs'
      - 'templates/**/*.cshtml'
      - 'templates/**/*.csproj'
      - 'templates/**/*.razor'
jobs:
  build-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 6.0.100

    - name: Build All
      run: .\build-all.ps1 -f
      working-directory: .\build
      shell: powershell

    - name: Test All
      run: .\test-all.ps1 -f
      working-directory: .\build
      shell: powershell

    - name: Codecov
      uses: codecov/codecov-action@v2
